FROM haproxy:1.7
COPY haproxy.http.cfg /usr/local/etc/haproxy/haproxy.cfg
COPY ./appgoto.pem /etc/ssl/private/appgoto.pem
COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]